# Generated by Django 4.0.2 on 2022-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haysite', '0002_rename_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
